-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 21:54:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myssi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myssi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myssi` DEFAULT CHARACTER SET latin1 ;
USE `myssi` ;

-- -----------------------------------------------------
-- Table `myssi`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`attachments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bind_type` VARCHAR(64) NOT NULL DEFAULT '',
  `bind_id` INT(11) NOT NULL DEFAULT '0',
  `file` VARCHAR(255) NULL DEFAULT NULL,
  `info` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`configuration` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`users_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `allow_view_all` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_projects` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_tasks` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_tickets` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_users` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_configuration` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_tasks_viewonly` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_discussions` TINYINT(1) NULL DEFAULT NULL,
  `allow_manage_discussions_viewonly` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_group_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `photo` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `culture` VARCHAR(5) NULL DEFAULT NULL,
  `password` VARCHAR(64) NOT NULL DEFAULT '',
  `active` TINYINT(1) NULL DEFAULT NULL,
  `skin` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pople_people_group` (`users_group_id` ASC),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`users_group_id`)
    REFERENCES `myssi`.`users_groups` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`departments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_departments_users` (`users_id` ASC),
  CONSTRAINT `fk_departments_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`projects_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`projects_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`projects_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`projects_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_status_id` INT(11) NULL DEFAULT NULL,
  `projects_types_id` INT(11) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL DEFAULT NULL,
  `team` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `order_tasks_by` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_projects_status` (`projects_status_id` ASC),
  INDEX `fk_projects_project_types` (`projects_types_id` ASC),
  INDEX `fk_projects_pople` (`created_by` ASC),
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`projects_status_id`)
    REFERENCES `myssi`.`projects_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `projects_ibfk_2`
    FOREIGN KEY (`projects_types_id`)
    REFERENCES `myssi`.`projects_types` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `projects_ibfk_3`
    FOREIGN KEY (`created_by`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`discussions_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`discussions_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`discussions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`discussions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `users_id` INT(11) NULL DEFAULT NULL,
  `discussions_status_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL DEFAULT NULL,
  `assigned_to` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `fk_discussions_projects` (`projects_id` ASC),
  INDEX `fk_discussions_users` (`users_id` ASC),
  INDEX `fk_discussions_discussions_status` (`discussions_status_id` ASC),
  CONSTRAINT `discussions_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discussions_ibfk_2`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `discussions_ibfk_3`
    FOREIGN KEY (`discussions_status_id`)
    REFERENCES `myssi`.`discussions_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`discussions_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`discussions_comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `discussions_id` INT(11) NOT NULL DEFAULT '0',
  `users_id` INT(11) NULL DEFAULT NULL,
  `discussions_status_id` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discussions_comments_discussions` (`discussions_id` ASC),
  INDEX `fk_discussions_comments_users` (`users_id` ASC),
  INDEX `fk_discussions_status_id` (`discussions_status_id` ASC),
  CONSTRAINT `discussions_comments_ibfk_1`
    FOREIGN KEY (`discussions_id`)
    REFERENCES `myssi`.`discussions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discussions_comments_ibfk_2`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `discussions_comments_ibfk_3`
    FOREIGN KEY (`discussions_status_id`)
    REFERENCES `myssi`.`discussions_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`discussions_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`discussions_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `display_on_home` TINYINT(1) NULL DEFAULT NULL,
  `projects_id` TEXT NULL DEFAULT NULL,
  `projects_type_id` TEXT NULL DEFAULT NULL,
  `projects_status_id` TEXT NULL DEFAULT NULL,
  `discussions_status_id` TEXT NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id` (`users_id` ASC),
  CONSTRAINT `discussions_reports_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`events` (
  `event_id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_name` TEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `details` TEXT NOT NULL,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`event_id`),
  INDEX `fk_events_users` (`users_id` ASC),
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`extra_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`extra_fields` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `bind_type` VARCHAR(64) NOT NULL DEFAULT '',
  `type` VARCHAR(64) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT '0',
  `active` TINYINT(1) NULL DEFAULT NULL,
  `display_in_list` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`extra_fields_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`extra_fields_list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `extra_fields_id` INT(11) NOT NULL DEFAULT '0',
  `bind_id` INT(11) NOT NULL DEFAULT '0',
  `value` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_extra_fields_list_extra_fields` (`extra_fields_id` ASC),
  CONSTRAINT `extra_fields_list_ibfk_1`
    FOREIGN KEY (`extra_fields_id`)
    REFERENCES `myssi`.`extra_fields` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`phases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`phases` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `default_values` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`phases_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`phases_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`projects_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`projects_comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `created_by` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_comments_projects` (`projects_id` ASC),
  INDEX `fk_projects_comments_pople` (`created_by` ASC),
  CONSTRAINT `projects_comments_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `projects_comments_ibfk_2`
    FOREIGN KEY (`created_by`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`projects_phases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`projects_phases` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `phases_status_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `due_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_phases_projects` (`projects_id` ASC),
  INDEX `fk_projects_phases_phases_status` (`phases_status_id` ASC),
  CONSTRAINT `projects_phases_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `projects_phases_ibfk_2`
    FOREIGN KEY (`phases_status_id`)
    REFERENCES `myssi`.`phases_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`projects_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`projects_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `display_on_home` TINYINT(1) NULL DEFAULT NULL,
  `projects_id` TEXT NULL DEFAULT NULL,
  `projects_type_id` TEXT NULL DEFAULT NULL,
  `projects_status_id` TEXT NULL DEFAULT NULL,
  `in_team` INT(11) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `display_in_menu` TINYINT(1) NULL DEFAULT NULL,
  `visible_on_home` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id` (`users_id` ASC),
  CONSTRAINT `projects_reports_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tickets_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tickets_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `group` VARCHAR(64) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `default_value` INT(11) NULL DEFAULT NULL,
  `active` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tickets_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tickets_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT NULL,
  `active` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `departments_id` INT(11) NULL DEFAULT NULL,
  `tickets_types_id` INT(11) NULL DEFAULT NULL,
  `tickets_status_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_users` (`users_id` ASC),
  INDEX `fk_tickets_tickets_status` (`tickets_status_id` ASC),
  INDEX `fk_tickets_tickets_types` (`tickets_types_id` ASC),
  INDEX `fk_tickets_projects` (`projects_id` ASC),
  INDEX `fk_tickets_departments` (`departments_id` ASC),
  CONSTRAINT `fk_tickets_tickets_status`
    FOREIGN KEY (`tickets_status_id`)
    REFERENCES `myssi`.`tickets_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_tickets_tickets_types`
    FOREIGN KEY (`tickets_types_id`)
    REFERENCES `myssi`.`tickets_types` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_tickets_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tickets_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tickets_ibfk_2`
    FOREIGN KEY (`departments_id`)
    REFERENCES `myssi`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `group` VARCHAR(64) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks_priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks_priority` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `icon` VARCHAR(64) NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks_labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks_labels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_groups_projects` (`projects_id` ASC),
  CONSTRAINT `tasks_groups_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`versions_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`versions_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `sort_order` INT(11) NULL DEFAULT '0',
  `default_value` TINYINT(1) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`versions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `versions_status_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_versions_versions_status` (`versions_status_id` ASC),
  INDEX `fk_versions_projects` (`projects_id` ASC),
  CONSTRAINT `versions_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `versions_ibfk_2`
    FOREIGN KEY (`versions_status_id`)
    REFERENCES `myssi`.`versions_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `projects_id` INT(11) NOT NULL DEFAULT '0',
  `tasks_status_id` INT(11) NULL DEFAULT NULL,
  `tasks_priority_id` INT(11) NULL DEFAULT NULL,
  `tasks_type_id` INT(11) NULL DEFAULT NULL,
  `tasks_label_id` INT(11) NULL DEFAULT NULL,
  `tasks_groups_id` INT(11) NULL DEFAULT NULL,
  `projects_phases_id` INT(11) NULL DEFAULT NULL,
  `versions_id` INT(11) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL DEFAULT NULL,
  `assigned_to` VARCHAR(255) NULL DEFAULT NULL,
  `estimated_time` FLOAT NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `tickets_id` INT(11) NULL DEFAULT NULL,
  `closed_date` DATE NULL DEFAULT NULL,
  `discussion_id` INT(11) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `progress` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_projects` (`projects_id` ASC),
  INDEX `fk_tasks_task_status` (`tasks_status_id` ASC),
  INDEX `fk_tasks_task_type` (`tasks_type_id` ASC),
  INDEX `fk_tasks_task_label` (`tasks_label_id` ASC),
  INDEX `fk_tasks_projects_phases` (`projects_phases_id` ASC),
  INDEX `fk_tasks_pople` (`created_by` ASC),
  INDEX `fk_tasks_tasks_groups` (`tasks_groups_id` ASC),
  INDEX `fk_tasks_versions` (`versions_id` ASC),
  INDEX `fk_tasks_tasks_priority` (`tasks_priority_id` ASC),
  INDEX `fk_tasks_tickets` (`tickets_id` ASC),
  CONSTRAINT `tasks_ibfk_1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `myssi`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_ibfk_10`
    FOREIGN KEY (`tickets_id`)
    REFERENCES `myssi`.`tickets` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_ibfk_2`
    FOREIGN KEY (`tasks_status_id`)
    REFERENCES `myssi`.`tasks_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_ibfk_3`
    FOREIGN KEY (`tasks_priority_id`)
    REFERENCES `myssi`.`tasks_priority` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_ibfk_4`
    FOREIGN KEY (`tasks_type_id`)
    REFERENCES `myssi`.`tasks_types` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_ibfk_5`
    FOREIGN KEY (`tasks_label_id`)
    REFERENCES `myssi`.`tasks_labels` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_ibfk_6`
    FOREIGN KEY (`tasks_groups_id`)
    REFERENCES `myssi`.`tasks_groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_ibfk_7`
    FOREIGN KEY (`projects_phases_id`)
    REFERENCES `myssi`.`projects_phases` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_ibfk_8`
    FOREIGN KEY (`versions_id`)
    REFERENCES `myssi`.`versions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_ibfk_9`
    FOREIGN KEY (`created_by`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tasks_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tasks_comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tasks_id` INT(11) NOT NULL DEFAULT '0',
  `created_by` INT(11) NULL DEFAULT NULL,
  `tasks_status_id` INT(11) NULL DEFAULT NULL,
  `tasks_priority_id` INT(11) NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `worked_hours` FLOAT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `progress` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_comments_pople` (`created_by` ASC),
  INDEX `fk_tasks_comments_tasks` (`tasks_id` ASC),
  INDEX `fk_tasks_comments_status` (`tasks_status_id` ASC),
  INDEX `fk_tasks_comments_priority` (`tasks_priority_id` ASC),
  CONSTRAINT `tasks_comments_ibfk_1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `myssi`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tasks_comments_ibfk_2`
    FOREIGN KEY (`created_by`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_comments_ibfk_3`
    FOREIGN KEY (`tasks_status_id`)
    REFERENCES `myssi`.`tasks_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tasks_comments_ibfk_4`
    FOREIGN KEY (`tasks_priority_id`)
    REFERENCES `myssi`.`tasks_priority` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tickets_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tickets_comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `tickets_id` INT(11) NOT NULL DEFAULT '0',
  `users_id` INT(11) NULL DEFAULT NULL,
  `tickets_status_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_comments_tickets` (`tickets_id` ASC),
  INDEX `fk_tickets_comments_users` (`users_id` ASC),
  INDEX `k_tickets_comments_status` (`tickets_status_id` ASC),
  CONSTRAINT `fk_tickets_comments_tickets`
    FOREIGN KEY (`tickets_id`)
    REFERENCES `myssi`.`tickets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tickets_comments_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `tickets_comments_ibfk_1`
    FOREIGN KEY (`tickets_status_id`)
    REFERENCES `myssi`.`tickets_status` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`tickets_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`tickets_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `display_on_home` TINYINT(1) NULL DEFAULT NULL,
  `projects_id` TEXT NULL DEFAULT NULL,
  `projects_type_id` TEXT NULL DEFAULT NULL,
  `projects_status_id` TEXT NULL DEFAULT NULL,
  `departments_id` TEXT NULL DEFAULT NULL,
  `tickets_types_id` TEXT NULL DEFAULT NULL,
  `tickets_status_id` TEXT NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id` (`users_id` ASC),
  CONSTRAINT `tickets_reports_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myssi`.`user_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myssi`.`user_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `display_on_home` TINYINT(1) NULL DEFAULT NULL,
  `projects_id` TEXT NULL DEFAULT NULL,
  `projects_type_id` TEXT NULL DEFAULT NULL,
  `projects_status_id` TEXT NULL DEFAULT NULL,
  `assigned_to` TEXT NULL DEFAULT NULL,
  `tasks_status_id` TEXT NULL DEFAULT NULL,
  `tasks_type_id` TEXT NULL DEFAULT NULL,
  `tasks_label_id` TEXT NULL DEFAULT NULL,
  `due_date_from` DATE NULL DEFAULT NULL,
  `due_date_to` DATE NULL DEFAULT NULL,
  `created_from` DATE NULL DEFAULT NULL,
  `created_to` DATE NULL DEFAULT NULL,
  `closed_from` DATE NULL DEFAULT NULL,
  `closed_to` DATE NULL DEFAULT NULL,
  `sort_order` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_reports_users` (`users_id` ASC),
  CONSTRAINT `user_reports_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myssi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
